# ZSTD ---------------------------------------------------------------------------
set(zstd_src
        thirdparty/zstd/dictBuilder/fastcover.c
        thirdparty/zstd/dictBuilder/zdict.c
        thirdparty/zstd/dictBuilder/cover.c
        thirdparty/zstd/dictBuilder/divsufsort.c
        thirdparty/zstd/compress/zstd_compress_literals.c
        thirdparty/zstd/compress/huf_compress.c
        thirdparty/zstd/compress/zstd_double_fast.c
        thirdparty/zstd/compress/zstd_lazy.c
        thirdparty/zstd/compress/zstd_compress_superblock.c
        thirdparty/zstd/compress/fse_compress.c
        thirdparty/zstd/compress/zstdmt_compress.c
        thirdparty/zstd/compress/zstd_compress_sequences.c
        thirdparty/zstd/compress/hist.c
        thirdparty/zstd/compress/zstd_opt.c
        thirdparty/zstd/compress/zstd_ldm.c
        thirdparty/zstd/compress/zstd_fast.c
        thirdparty/zstd/compress/zstd_compress.c
        thirdparty/zstd/common/entropy_common.c
        thirdparty/zstd/common/pool.c
        thirdparty/zstd/common/debug.c
        thirdparty/zstd/common/xxhash.c
        thirdparty/zstd/common/fse_decompress.c
        thirdparty/zstd/common/error_private.c
        thirdparty/zstd/common/zstd_common.c
        thirdparty/zstd/common/threading.c
        thirdparty/zstd/decompress/zstd_decompress.c
        thirdparty/zstd/decompress/zstd_decompress_block.c
        thirdparty/zstd/decompress/huf_decompress.c
        thirdparty/zstd/decompress/zstd_ddict.c
        thirdparty/zstd/dictBuilder/cover.h
        thirdparty/zstd/dictBuilder/divsufsort.h
        thirdparty/zstd/compress/zstd_compress_internal.h
        thirdparty/zstd/compress/zstd_compress_literals.h
        thirdparty/zstd/compress/zstd_fast.h
        thirdparty/zstd/compress/zstd_cwksp.h
        thirdparty/zstd/compress/zstdmt_compress.h
        thirdparty/zstd/compress/zstd_compress_superblock.h
        thirdparty/zstd/compress/zstd_compress_sequences.h
        thirdparty/zstd/compress/zstd_double_fast.h
        thirdparty/zstd/compress/zstd_ldm.h
        thirdparty/zstd/compress/zstd_ldm_geartab.h
        thirdparty/zstd/compress/zstd_lazy.h
        thirdparty/zstd/compress/zstd_opt.h
        thirdparty/zstd/compress/hist.h
        thirdparty/zstd/common/debug.h
        thirdparty/zstd/common/bitstream.h
        thirdparty/zstd/common/zstd_trace.h
        thirdparty/zstd/common/fse.h
        thirdparty/zstd/common/threading.h
        thirdparty/zstd/common/error_private.h
        thirdparty/zstd/common/cpu.h
        thirdparty/zstd/common/zstd_deps.h
        thirdparty/zstd/common/xxhash.h
        thirdparty/zstd/common/huf.h
        thirdparty/zstd/common/pool.h
        thirdparty/zstd/common/mem.h
        thirdparty/zstd/common/compiler.h
        thirdparty/zstd/common/zstd_internal.h
        thirdparty/zstd/decompress/zstd_ddict.h
        thirdparty/zstd/decompress/zstd_decompress_internal.h
        thirdparty/zstd/decompress/zstd_decompress_block.h
        thirdparty/zstd/zdict.h
        thirdparty/zstd/zstd.h
        thirdparty/zstd/zstd_errors.h
        )
